version: '3.8'

services:
  persian-legal-ai-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: persian-legal-ai-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "5173:5173"  # Vite dev server port
    environment:
      - NODE_ENV=development
      - DATABASE_PATH=/app/data/database.sqlite
      - SERVER_PORT=8080
      - PORT=8080
      - DEBUG=persian-legal:*
    volumes:
      - persian-legal-data-dev:/app/data
      - ./src:/app/src:ro           # Mount source for hot reload
      - ./server:/app/server:ro     # Mount server for hot reload
      - ./docs:/app/docs:ro         # Mount built frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - persian-legal-dev-network
    command: >
      sh -c "
        echo 'Starting development server...' &&
        node server/index.js
      "

  # Optional: Database admin interface
  db-admin:
    image: adminer:4.8.1
    container_name: persian-legal-db-admin
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=sqlite:///app/data/database.sqlite
    volumes:
      - persian-legal-data-dev:/app/data:ro
    networks:
      - persian-legal-dev-network
    depends_on:
      - persian-legal-ai-dev
    profiles:
      - admin

networks:
  persian-legal-dev-network:
    driver: bridge
    name: persian-legal-dev-network

volumes:
  persian-legal-data-dev:
    driver: local
    name: persian-legal-data-dev