services:
  backend:
    build:
      context: .
      target: backend
    container_name: newbolt-backend
    ports:
      - "3000:3000"            # (aligns with actual runtime port from logs)
    env_file:
      - .env.development
    volumes:
      - backend-data:/app/data # (named volume; avoids Windows bind-mount issues with SQLite)
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks: [app-network]

  frontend:
    build:
      context: .
      target: frontend
    container_name: newbolt-frontend
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks: [app-network]

networks:
  app-network:
    driver: bridge

volumes:
  backend-data: {}  # (named volume lives inside Docker; safe for SQLite WAL)