# NewBolt AI Learn - Development Docker Compose
# Optimized for development with hot reload and debugging

version: '3.8'

services:
  # ===== Development Backend =====
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: persian-legal-ai-backend-dev
    ports:
      - "8000:3000"  # Map host port 8000 to container port 3000
      - "9229:9229"  # Node.js debug port
    environment:
      - NODE_ENV=development
      - PORT=3000
      - SERVER_PORT=3000
      - HOST=0.0.0.0
      - SERVE_FRONTEND=false
      - DATABASE_PATH=/app/data/database.sqlite
      - DB_PATH=/app/data/database.sqlite  # Legacy compatibility
      - JWT_SECRET=dev-jwt-secret-not-secure
      - SESSION_SECRET=dev-session-secret-not-secure
      - CSRF_SECRET=dev-csrf-secret-not-secure
      - DEBUG=true
      - TF_CPP_MIN_LOG_LEVEL=2
    volumes:
      - .:/app
      - /app/node_modules
      - ./data:/app/data
      - ./datasets:/app/datasets
      - ./models:/app/models
      - ./checkpoints:/app/checkpoints
      - ./exports:/app/exports
      - ./logs:/app/logs
    command: npm run dev
    restart: unless-stopped
    networks:
      - newboltailearn-dev-network
    labels:
      - "app=newboltailearn"
      - "component=backend-dev"

  # ===== Development Frontend =====
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: persian-legal-ai-frontend-dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000  # Point to backend on host port 8000
      - VITE_BASE_PATH=/
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    restart: unless-stopped
    depends_on:
      - backend-dev
    networks:
      - newboltailearn-dev-network
    labels:
      - "app=newboltailearn"
      - "component=frontend-dev"

  # ===== Redis for Development =====
  redis-dev:
    image: redis:7-alpine
    container_name: newboltailearn-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    restart: unless-stopped
    networks:
      - newboltailearn-dev-network
    labels:
      - "app=newboltailearn"
      - "component=redis-dev"

  # ===== Database Admin (Optional) =====
  db-admin:
    image: adminer
    container_name: persian-legal-ai-db-admin
    ports:
      - "8081:8080"  # Use port 8081 to avoid conflict with frontend
    environment:
      - ADMINER_DEFAULT_SERVER=sqlite:///app/data/database.sqlite
    volumes:
      - ./data:/app/data:ro
    restart: unless-stopped
    networks:
      - newboltailearn-dev-network
    profiles:
      - admin
    labels:
      - "app=newboltailearn"
      - "component=db-admin"

volumes:
  redis_dev_data:
    driver: local

networks:
  newboltailearn-dev-network:
    driver: bridge