version: '3.8'

services:
  backend:
    build:
      context: .
      target: backend
    container_name: newbolt-backend
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    volumes:
      - backend-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build:
      context: .
      target: frontend
    container_name: newbolt-frontend
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

volumes:
  backend-data:
    driver: local