services:
  backend:
    build:
      context: .
      target: backend
    container_name: persian-legal-ai-backend
    ports:
      - "8080:8080"            # Map host port 8080 to container port 8080
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/app/data/database.sqlite
      - SERVER_PORT=8080
      - PORT=8080
      - CORS_ORIGIN=http://localhost:8080
    volumes:
      - backend-data:/app/data # Named volume for SQLite database persistence
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 60s        # Give more time for database initialization
    restart: unless-stopped
    networks: [app-network]


networks:
  app-network:
    driver: bridge

volumes:
  backend-data:
    driver: local
    # Named volume for SQLite database persistence with WAL mode support