version: '3.8'

services:
  persian-legal-ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: persian-legal-ai
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/app/data/database.sqlite
      - SERVER_PORT=8080
      - PORT=8080
    volumes:
      - persian-legal-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - persian-legal-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.persian-legal.rule=Host(`localhost`)"
      - "traefik.http.services.persian-legal.loadbalancer.server.port=8080"

networks:
  persian-legal-network:
    driver: bridge
    name: persian-legal-network

volumes:
  persian-legal-data:
    driver: local
    name: persian-legal-data