services:
  backend:
    build:
      context: .
      target: backend
    container_name: persian-legal-ai-backend
    ports:
      - "8000:8000"            # Map host port 8000 to container port 8000
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/app/data/database.sqlite
      - SERVER_PORT=8000
      - PORT=8000
      - CORS_ORIGIN=http://localhost:8080
    volumes:
      - backend-data:/app/data # Named volume for SQLite database persistence
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 60s        # Give more time for database initialization
    restart: unless-stopped
    networks: [app-network]

  frontend:
    build:
      context: .
      target: frontend
    container_name: persian-legal-ai-frontend
    ports:
      - "8080:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks: [app-network]

networks:
  app-network:
    driver: bridge

volumes:
  backend-data:
    driver: local
    # Named volume for SQLite database persistence with WAL mode support