services:
  - type: web
    name: newboltailearn-backend
    env: node
    plan: free
    region: frankfurt
    buildCommand: "echo '🔧 Build started with Node' $(node -v) && rm -rf node_modules package-lock.json || true && npm cache clean --force && npm ci --prefer-offline --no-audit && npm run render:verify-abi && echo '✅ Build completed successfully'"
    startCommand: "echo '🚀 Starting with Node' $(node -v) && npm run render:verify-abi && node server.js"
    envVars:
      - key: NODE_VERSION
        value: 20.17.0
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: DB_PATH
        value: ./persian_legal_ai.db
      - key: NPM_CONFIG_AUDIT
        value: false
      - key: NPM_CONFIG_FUND
        value: false
    autoDeploy: true