services:
  - type: web
    name: newboltailearn-backend
    env: node
    plan: free
    region: frankfurt
    buildCommand: "npm ci && npm cache clean --force"
    startCommand: "node server.js"
    envVars:
      - key: NODE_VERSION
        value: 20.17.0
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: DB_PATH
        value: ./persian_legal_ai.db
    autoDeploy: true